name: Prepare local env
description: Prepare local environment by setup node, and cache dependencies
outputs:
  cache-hit:
    description: Whether the dependencies were cached
    value: ${{ steps.npm-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Setup Node
      # Use Node version specified in Volta config inside package.json
      uses: volta-cli/action@v4
    - name: Get npm cache directory
      shell: bash
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"
    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: |
          **/node_modules
          ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
