export enum CustomBg {
  DegenPoet1 = "DegenPoet#1",
  Rgb0x001 = "rgb0x00#1",
  Retardio1 = "Retardio#1",
  Retardio2 = "Retardio#2",
  Retardio3 = "Retardio#3",
  NumberArt0 = "NumberArt#0",
  NumberArt1 = "NumberArt#1",
  NumberArt2 = "NumberArt#2",
  NumberArt3 = "NumberArt#3",
  NumberArt4 = "NumberArt#4",
  NumberArt5 = "NumberArt#5",
  NumberArt6 = "NumberArt#6",
  NumberArt7 = "NumberArt#7",
  NumberArt8 = "NumberArt#8",
  NumberArt9 = "NumberArt#9",
  ValentineDay2025 = "Valentine'sDay2025",
}
